name: Setup

defaults:
  run:
    shell: bash

runs:
  using: composite
  steps:
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: 20
        cache: 'npm'

    - run: npm ci
